### ISSUE TITLE
DriverPackageNotInstalledError: SQLite package has not been found installed

### ISSUE THREAD

**Issue by tmrstian** [shanmugharajk/react-point-of-sale#22]
Hi,

I installed both web and api parts, but I get the following error message when running the "yarn dev:api".
What did i miss?

Thank you,
/S

[nodemon] starting `ts-node ./src/index.ts`
**DriverPackageNotInstalledError: SQLite package has not been found installed.** Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/error/DriverPackageNotInstalledError.ts:8:9)
    at SqliteDriver.loadDependencies (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/driver/sqlite/SqliteDriver.ts:112:19)
    at new SqliteDriver (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/driver/sqlite/SqliteDriver.ts:46:14)
    at DriverFactory.create (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/driver/DriverFactory.ts:32:24)
    at new Connection (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/connection/Connection.ts:122:43)
    at ConnectionManager.create (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/connection/ConnectionManager.ts:64:28)
    at Object.<anonymous> (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/src/index.ts:218:35)
    at step (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/node_modules/typeorm/index.js:32:23)
    at Object.next (/Users/svaelitalo/Downloads/react-point-of-sale-master/api/node_modules/typeorm/index.js:13:53)
    at /Users/svaelitalo/Downloads/react-point-of-sale-master/api/node_modules/typeorm/index.js:7:71
[nodemon] clean exit - waiting for changes before restart

**Comment by Ahmedka114** [comment]
just navigate into api, and run "yarn add sqlite3 --save"

**Comment by shanmugharajk** [comment]
Sorry was not monitoring this repo. I'm doing a revamp of this app now for a personal use case in Remix, drizzle, shadcn. Will release that soon.
